{% set version = '1.4-5' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-abind
  version: {{ version|replace("-", "_") }}

source:
  fn: abind_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/abind_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/abind/abind_{{ version }}.tar.gz
  sha256: 3a3ace5afbcb86e56889efcebf3bf5c3bb042a282ba7cc4412d450bb246a3f2c

build:
  noarch: generic
  merge_build_host: True  # [win]
  number: 1000
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{posix}}zip               # [win]
  host:
    - r-base
  run:
    - r-base

test:
  commands:
    - $R -e "library('abind')"           # [not win]
    - "\"%R%\" -e \"library('abind')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=abind
  license: LGPL (>= 2)
  summary: Combine multidimensional arrays into a single array. This is a generalization of 'cbind'
    and 'rbind'.  Works with vectors, matrices, and higher-dimensional arrays.  Also
    provides functions 'adrop', 'asub', and 'afill' for manipulating, extracting and
    replacing data in arrays.
  license_family: LGPL

extra:
  recipe-maintainers:
    - qwhelan
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - dbast
