travis:
  secure:
    BINSTAR_TOKEN: F0JnJgBibhBbxWDaqBqJAxIVsjtEdSbIxdO6E9hK4IY2ocy35MvL5dH79H20BSQWyEN1CffkRwHfHApRBxlV87cKi1M5BT7bFrCIyrtXJojJSRkuK8APintPO7ZndQyH+oApiE+xwcwfee/FYchmHIUqxVSzvGh/6vUKQ02gqw4hsNwbzLpxkUXRb29C4gz1kDt8zevqHM6Nt9UCI1/Yj5wO3YmKGo2BBG3KcrEHBGQKt26sfta9FvaqvZnPGgJ4iT/h2HMJXGQie+dG8PwxZjmm6LN9ZViCWR2ICEKck8GuyfAbt+/iUfAD66FiBclwfKjl0apb88+MzqP0A2bg9kT/MP5DXuHEN4unISeYnlOD3kLLm9manQ8v1o5xwM/O7ydHvCvVgfo7UU0BSouzYLFlJ0JtLMtuR2YXq4qk5nHSTtEgBDCmr8/HSsPhUkyPUm2lRusN7abntmUlc3SSG8H1Ghvrt+PkXNCjDKwiI2XvmQLeG3xUYo5C6IoNg3xsC/zF+qW/76bR8Zsq27zO+yPPl8/Z3/xBNPS3Y4EeqFYpZrS+6080OtQfSkSAv0cf9Kr6uYmEpJspXFabPdss97cLAY2WgYaTfj8a549pDSkIZMzkKjz4/tA0TVLRV+M1YcIjvbGolWngFWdBS2+4/cW0M1sbuMnNAKDqqJSphCc=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
