travis:
  secure:
    BINSTAR_TOKEN: K8CxQr5A/v5SZL5CYVQ/Ulkqe/nHk8ESEgtB8cT8bBt2+8rS3+zIJsC0jW1pWG6fdaWlfWuw1AqZDM6cOglE1h8d0q74w/WjrUgz97Tj6RFVdyUM3TPHyfJjXudD39B6E9Smx5+lCN/Dl2vSvPx5F8x+xutkrBPYacDmACQZCPHMa6p4fKJB33WdfcKpiJ9hSysqzCTWhrgsxcqgpycEYPOqpisaGAr+5Hhfis74J9ccWHSwChIa1e+TpAZdl/j3352LH7RqrW4ClXnakF9WWwE9Z0rAVJw65MgMFpEdpeG4y1WVl1m+WrX9KEVnRR3AUnad+si3rlR/PESOvf3Z6xVRY+yCy15IMXYxBZuJgMHYaDGMvOCZBZfAfgWA08psChy9neqU9MOhHiv5QzS6f6WIny7bK1YSHTeTxcdbcqg/3AyUhCdU7qSmOlsoAbyMV4UQTSCWsT7pE2QgqYmeFKYSDsTyh0SSQb0mPnaw2Faf7WmvMIFvj98Z0/5/FF0nXXrDubBopqXPfeQSGl5/oZ8uL16n76t76HZ6acCL3y653uT0Lj20Kj3xrZqD6nTb/pfwTHaSr5rP/is+KCj9Gj38U40Jwy08+lm+d+7y3hUNbxOUdkFOyreidGlRlqhud8IJj03Wd/qKz6ATvPFhKBQydJA35j9RjdEBfsOMT34=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
