travis:
  secure:
    BINSTAR_TOKEN: Nyn7C0wU36AIMrM3yXu9olBQrvM+9LzmWYa6Qs0kt6Rj5KfIQKqOI/9rniXHoHA6I3EPn5vzxJyIhq5tHFwKjMpSL694afwGYCDaBQ2NQaznWegs5cuUZPSf6rC5UW4WDJWLMAplYpnSCCCaKkDeDsRr1ek70W1xYUVnvqo2l2Nul9LYMJ0JcY4kQ5JpzJdj8N/Uvgi69teAVLn9xUoli3wLdTt9sqdYHAX8Vn+8WPe5qh4+S4CYo2RiiiIYGhV6PU2sWaBPRtRSL+cdBHQsIeEFaBc9H4CTSBYMf2BdQ9spcdAKKSyPDyBi5yh15G8io+cb3ZAN9Fp1yne8twyLgQeBNgN0doonP0cQ2sevTg6wMiesw/lfo4DrZMg3BZYkQzhC0pwp0cnrX/NW05/V13UN2fKzKHiBjH7t5EQb+K95YDgllgZZ0geMTyPbzXuPAQfNBoI+JG4ih0yVo0uU8h/9FwkM6uQwmG0VKN/EfLOVWC4O1LZYFwAOJecFhW1N9XH8md7FW1a2MGfmSsYX0ttTBNi0gsIxVBKVINGxRT9nz9VSko/lIMZ8o26akPSbL6x6QasAZERjbcCwWXdgtBJ7IZ64bmhjuEL3rVx5QFmA8LK/blL4kVhpiHbGdn1GYNLNbJvOyuYwgit0rIY6MlfV1YKM72I8EaMvFro1ulo=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
