travis:
  secure:
    BINSTAR_TOKEN: CJ5ylgkc4/QXWHlxdZdgqFkSdaIunhQkJFQXPFd/dZAJE3jGKkXTYDhmuyvG8oljr/ODnozN2EYyZ+05xTA5m1iaSnRaybOPLKTdg+UjpFF7iH1lanSWEaqVIe2GzYkfZkf7+VmXf7CEepOfpp+24xDD/awzWfgUOA/+YwKgy7E3EZba4DV2iDNafgMAppZk9q9jiCC1/jIjHBlCNwG2quvQvkm7dlu3nngMtDr4y2WyQO6rXWxuMSOIMr/IlXn8AMlQ8N9VpPc7NiGphwr3/mT7cZTOqFFoXC4RAe8F7cR/L/dGKga1mTxPNv0ICWGqch+nH8Ao4EkGU9/bJ6xBUAb70jRMq+2UYcOliOWYTKfsf7wWuKGEtz9sakwCyH1qgQpWyUNJbDyq4OqcE14UvRvxDdZJEHpMT6QQEbojGaUP/ysGF0W7yVMJb/QSq8UBYPGnTWEmQ0LRSCdlDYe4zfme6VvBcfwPq0/BLh8ZuPxC9leHHEveI6Jab+JkT9lCgnjnUPw+s4XpUpTZD9DrK6/Hm+J8zBl2g8OTljxQbfbOVl9UsrxD2hYOwf0qSh4buFOR2FDAhmrLt4OeHMYtlbBQ7F3Bib5jOgIJRGz5eJkG0JoWfVkIaVbyY4OxwpZAh1nx7FVUCvzT1gSt5p1Q/yAmdOnTEA/BqOGSmDEq8K4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
