appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: JW7OR3XDNDWWiYIM2FAnZN/bA2mSm0lOQs8XqxC7OYz38OmunHzFSH/6umkPPZ0GSPy+LcyHGMoaNh7jHRPpQjsmjtsHWOH0+uw1lwwtS/MAgDdJtb8YYo5jq+eJ3hZMhy9NKEj19n7LsAEzHRYug8cIRYO5MMXhNXXMFGzCraxhk07qEnijFjL1xwvIGaD6Rh0e6p1iqXC16ZIOfNW+L618lgdAbqchi6FGda7LO7k7o1Y5BqEgyENMGwqhxYhTTPowLexp58NSYDoD2GYxVeXAvpfZqsHd9l7vO/EVA3WLJHA37WRw21KdjWzL/4cFb58MPDV1XOEKLHyeYrsLLkOkUEDTEQ/hQZyif3TpVh8fL2jRQja026nJUa+YUIqXbW3Wlm9ibcz7+eWLmKnmzcwqcyJPRXNyzN410wplfOZGdPCeslwwA54Ff1122n/xNjnxmJhdfFdQS04P9gTioKs9LXQnw+1N/SK/3uzJJpFWyghT0U5JqIFTD9FwAa2UO986vSQ4OIb39KXvfD7p4uOMaIyHP8v6hKhpn2pr+kPpzrfGxjUey2d3gxNw/GqvTAGd9eSe0+d32kJPgXvtGHrSeN2mPtMrpYDbyM5iGLa78xvwksiRgNftOCyvuFgvM4RtECxdAoKBtQFkGBoiWJqwtel9ad0Gi3MX2qn3aNY=
